# Generated by Django 2.2.16 on 2022-06-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20220607_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equation',
        ),
    ]
