# Generated by Django 2.2.16 on 2022-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_delete_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='result',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='a',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='number',
            name='b',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='number',
            name='c',
            field=models.IntegerField(default=24),
        ),
    ]
