# Generated by Django 2.2.16 on 2022-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20220607_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='a',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='number',
            name='b',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='number',
            name='c',
            field=models.IntegerField(default=13),
        ),
    ]
