# Generated by Django 2.2.16 on 2022-06-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20220607_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='a',
            field=models.IntegerField(default=-97),
        ),
        migrations.AlterField(
            model_name='number',
            name='b',
            field=models.IntegerField(default=-97),
        ),
        migrations.AlterField(
            model_name='number',
            name='c',
            field=models.IntegerField(default=-97),
        ),
    ]
