# Generated by Django 2.2.16 on 2022-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20220607_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='c',
            field=models.IntegerField(default=0),
        ),
    ]
