# Generated by Django 2.2.16 on 2022-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20220607_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='result',
            new_name='result1',
        ),
        migrations.AddField(
            model_name='number',
            name='result2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
